=head1 NAME

Perlcast Interview 008 - Interview with Shane Caraveo

=head1 ABSTRACT

At OSCON 2005 I got to interview Shane Caraveo. Shane is a senior developer at 
ActiveState where he is the technical lead for the Komodo IDE. In the 
interview, we talk about Komodo and Perl.

The audio of this interview can be found at 
L<Perlcast.com|http://www.perlcast.com/audio/Perlcast_Interview_008_Caraveo.mp3>.

=head1 PRELUDE

B<Josh>: 

=head1 INTERVIEW

B<Josh>: 

=head1 EPILOGUE

B<Josh>: 

=head1 BUGS AND LIMITATIONS

I tried to faithfully transcribe the interview, but quite likely got some
things wrong.  Corrections and other feedback are most welcome.

=head1 AUTHOR


=head1 LICENCE AND COPYRIGHT

Copyright (c) 2005.  All rights reserved.

Content of this interview: Copyright (c) 2005 Perlcast (perlcast at gmail dot
com).

You can redistribute and/or modify this document under the same terms as the
audio itself.

L<Contents|Perlcast::Interviews>
L<Previous|Perlcast::Interviews::007>
L<Next|Perlcast::Interviews::009>

